#!/usr/bin/env python3
"""
Cloud-friendly Excel workflow for this vault.

Cursor / GitHub / Obsidian cannot edit .xlsx as a spreadsheet. This script
keeps the workbook as the formula engine and uses a markdown sidecar as the
edit surface (blue input cells).

Usage:
    .venv/bin/python scripts/xlsx_model.py list
    .venv/bin/python scripts/xlsx_model.py show
    .venv/bin/python scripts/xlsx_model.py dump
    .venv/bin/python scripts/xlsx_model.py apply
    .venv/bin/python scripts/xlsx_model.py set '01_Inputs!B6=35'
    .venv/bin/python scripts/xlsx_model.py sheet 01_Inputs
    .venv/bin/python scripts/xlsx_model.py recalc
    .venv/bin/python scripts/xlsx_model.py check
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any, Iterator, Sequence

from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

VAULT_ROOT = Path(__file__).resolve().parents[1]
SKIP_DIR_NAMES = {".venv", ".git", "node_modules", ".trash"}
SIDECAR_SUFFIX = " Inputs.md"
CELL_REF_RE = re.compile(r"^(.+?)!([A-Za-z]+[0-9]+)$")
SET_RE = re.compile(r"^(.+?)!([A-Za-z]+[0-9]+)=(.*)$")
GENERATED_NOTE = (
    "_Generated by `scripts/xlsx_model.py`. Do not edit this section; "
    "it is rewritten on dump/apply/set/recalc._"
)


@dataclass(frozen=True)
class InputCell:
    sheet: str
    coordinate: str
    value: Any
    label: str = ""
    unit: str = ""


def iter_xlsx_files(root: Path = VAULT_ROOT) -> Iterator[Path]:
    for path in sorted(root.rglob("*.xlsx")):
        if any(part in SKIP_DIR_NAMES for part in path.parts):
            continue
        if path.name.startswith("~$"):
            continue
        yield path


def resolve_workbook(query: str | None, root: Path = VAULT_ROOT) -> Path:
    files = list(iter_xlsx_files(root))
    if not files:
        raise SystemExit("No .xlsx workbooks found in the vault.")
    if query in (None, "", "default"):
        for path in files:
            if path.stem == "GEO Complete Investment Model":
                return path
        if len(files) == 1:
            return files[0]
        listed = "\n".join(f"  {p.relative_to(root)}" for p in files)
        raise SystemExit(f"Pass a workbook name. Available:\n{listed}")

    candidate = Path(query).expanduser()
    if candidate.exists():
        return candidate.resolve()
    vault_candidate = (root / query).resolve()
    if vault_candidate.exists():
        return vault_candidate

    q = query.lower().removesuffix(".xlsx")
    matches = [
        p
        for p in files
        if q == p.stem.lower()
        or q in p.stem.lower()
        or q in str(p.relative_to(root)).lower()
    ]
    if len(matches) == 1:
        return matches[0]
    if not matches:
        listed = "\n".join(f"  {p.relative_to(root)}" for p in files)
        raise SystemExit(f"No workbook matching {query!r}. Available:\n{listed}")
    listed = "\n".join(f"  {p.relative_to(root)}" for p in matches)
    raise SystemExit(f"Ambiguous workbook {query!r}:\n{listed}")


def sidecar_path(workbook: Path) -> Path:
    return workbook.with_name(workbook.stem + SIDECAR_SUFFIX)


def font_rgb(cell) -> str | None:
    color = cell.font.color if cell.font is not None else None
    if color is None:
        return None
    rgb = getattr(color, "rgb", None)
    if not rgb:
        return None
    return str(rgb).upper()


def is_blue_input(cell) -> bool:
    if cell.value is None:
        return False
    if isinstance(cell.value, str) and cell.value.startswith("="):
        return False
    rgb = font_rgb(cell)
    return bool(rgb) and rgb.endswith("0000FF")


def is_formula(value: Any) -> bool:
    return isinstance(value, str) and value.startswith("=")


GENERIC_HEADERS = {"parameter", "value", "unit", "notes", "item", "output"}


def nearest_column_header(ws: Worksheet, row: int, col: int) -> str:
    for r in range(row - 1, 0, -1):
        value = ws.cell(r, col).value
        if value in (None, ""):
            return ""
        if not isinstance(value, str):
            continue
        text = value.strip()
        if not text or text.startswith("=") or text.lower() in GENERIC_HEADERS:
            continue
        return text
    return ""


def cell_label(ws: Worksheet, cell) -> str:
    row_label = ws.cell(cell.row, 1).value
    row_text = str(row_label).strip() if row_label not in (None, "") else ""
    header = nearest_column_header(ws, cell.row, cell.column)
    if header.lower() in GENERIC_HEADERS:
        header = ""
    if row_text and header:
        return f"{row_text} / {header}"
    return row_text or header


def cell_unit(ws: Worksheet, cell) -> str:
    if cell.column != 2:
        return ""
    unit = ws.cell(cell.row, 3).value
    if unit in (None, "") or is_formula(unit) or not isinstance(unit, str):
        return ""
    return unit.strip()


def iter_blue_cells(wb) -> list[InputCell]:
    found: list[InputCell] = []
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for row in ws.iter_rows(
            min_row=1, max_row=ws.max_row, max_col=ws.max_column
        ):
            for cell in row:
                if not is_blue_input(cell):
                    continue
                found.append(
                    InputCell(
                        sheet=sheet_name,
                        coordinate=cell.coordinate,
                        value=cell.value,
                        label=cell_label(ws, cell),
                        unit=cell_unit(ws, cell),
                    )
                )
    return found


def iter_constant_numeric_cells(wb) -> list[InputCell]:
    found: list[InputCell] = []
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for row in ws.iter_rows(
            min_row=1, max_row=ws.max_row, max_col=ws.max_column
        ):
            for cell in row:
                if cell.value is None or is_formula(cell.value):
                    continue
                if not isinstance(cell.value, (int, float)) or isinstance(
                    cell.value, bool
                ):
                    continue
                found.append(
                    InputCell(
                        sheet=sheet_name,
                        coordinate=cell.coordinate,
                        value=cell.value,
                        label=cell_label(ws, cell),
                        unit=cell_unit(ws, cell),
                    )
                )
    return found


def collect_input_cells(wb) -> tuple[list[InputCell], str]:
    blue = iter_blue_cells(wb)
    if blue:
        return blue, "blue"
    return iter_constant_numeric_cells(wb), "numeric"


def fmt_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        if value.is_integer() and abs(value) < 1e12:
            return str(int(value))
        return format(value, ".16g")
    if isinstance(value, datetime):
        return value.isoformat(sep=" ", timespec="seconds")
    if isinstance(value, date):
        return value.isoformat()
    text = str(value).replace("\n", " ").replace("|", "\\|")
    return text


def parse_value(raw: str) -> Any:
    text = raw.strip()
    if text == "":
        return None
    if text.startswith("="):
        return text
    lowered = text.lower()
    if lowered == "true":
        return True
    if lowered == "false":
        return False
    if re.fullmatch(r"-?\d+", text):
        return int(text)
    if re.fullmatch(r"-?\d+\.\d+", text) or re.fullmatch(
        r"-?\d+(\.\d+)?[eE][+-]?\d+", text
    ):
        return float(text)
    return text.replace("\\|", "|")


def md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def cover_sheet_name(sheet_names: Sequence[str]) -> str | None:
    for name in sheet_names:
        if "cover" in name.lower():
            return name
    return sheet_names[0] if sheet_names else None


def load_formualizer(path: Path):
    try:
        import formualizer as fz
    except ImportError as exc:
        raise SystemExit(
            "Missing dependency formualizer. Install with:\n"
            "  .venv/bin/pip install -r requirements.txt"
        ) from exc
    return fz.load_workbook(str(path))


def live_outputs(path: Path) -> list[tuple[str, Any]]:
    wb = load_formualizer(path)
    cover = cover_sheet_name(wb.sheet_names)
    if not cover:
        return []
    openpyxl_wb = load_workbook(path, data_only=False)
    ws = openpyxl_wb[cover]
    rows: list[tuple[str, Any]] = []
    max_row = ws.max_row or 0
    for row in range(1, max_row + 1):
        label = ws.cell(row, 1).value
        value_cell = ws.cell(row, 2)
        if not label or value_cell.value is None:
            continue
        computed = wb.evaluate_cell(cover, row, 2)
        rows.append((str(label), computed))
    return rows


def recalc_file(path: Path) -> dict[str, Any]:
    try:
        import formualizer as fz
    except ImportError as exc:
        raise SystemExit(
            "Missing dependency formualizer. Install with:\n"
            "  .venv/bin/pip install -r requirements.txt"
        ) from exc
    summary = fz.recalculate_file(str(path))
    if summary.get("status") != "success" or summary.get("errors"):
        raise SystemExit(f"Recalculate failed: {summary}")
    return summary


def write_cell(ws: Worksheet, coordinate: str, value: Any) -> None:
    cell = ws[coordinate]
    cell.value = value


def apply_cells(path: Path, cells: Sequence[InputCell]) -> int:
    wb = load_workbook(path)
    changed = 0
    for item in cells:
        if item.sheet not in wb.sheetnames:
            raise SystemExit(f"Unknown sheet {item.sheet!r} in {path.name}")
        ws = wb[item.sheet]
        current = ws[item.coordinate].value
        if values_close(current, item.value):
            continue
        write_cell(ws, item.coordinate, item.value)
        changed += 1
    if changed:
        wb.save(path)
    return changed


def render_markdown(
    workbook: Path,
    cells: Sequence[InputCell],
    mode: str,
    outputs: Sequence[tuple[str, Any]],
) -> str:
    try:
        rel = workbook.resolve().relative_to(VAULT_ROOT)
    except ValueError:
        rel = workbook
    apply_cmd = ".venv/bin/python scripts/xlsx_model.py apply"
    if workbook.stem != "GEO Complete Investment Model":
        apply_cmd += f' -w "{workbook.stem}"'
    wikilink = workbook.stem
    lines = [
        f"Cloud-editable inputs for [[{wikilink}]]. Edit the **Value** column, then apply:",
        "",
        "```",
        apply_cmd,
        "```",
        "",
        "Blue / input cells only — formulas stay in the `.xlsx`. After editing the workbook in Excel, run `dump` to refresh this file.",
        "",
        f"Workbook path: `{rel.as_posix()}`",
        "",
        "## Live outputs",
        "",
        GENERATED_NOTE,
        "",
        "| Output | Value |",
        "| --- | ---: |",
    ]
    if outputs:
        for label, value in outputs:
            lines.append(f"| {md_escape(label)} | {fmt_value(value)} |")
    else:
        lines.append("| _(none)_ | |")

    by_sheet: dict[str, list[InputCell]] = {}
    for cell in cells:
        by_sheet.setdefault(cell.sheet, []).append(cell)

    mode_label = (
        "blue input cells" if mode == "blue" else "numeric constant cells (no blue styling)"
    )
    lines.extend(["", f"## Inputs ({mode_label})", ""])
    if not cells:
        lines.append("_No editable input cells found._")
        lines.append("")
        return "\n".join(lines)

    for sheet, sheet_cells in by_sheet.items():
        lines.extend(
            [
                f"### {sheet}",
                "",
                "| Sheet | Cell | Label | Value | Unit |",
                "| --- | --- | --- | ---: | --- |",
            ]
        )
        for cell in sheet_cells:
            lines.append(
                "| {sheet} | {coord} | {label} | {value} | {unit} |".format(
                    sheet=md_escape(cell.sheet),
                    coord=cell.coordinate,
                    label=md_escape(cell.label),
                    value=fmt_value(cell.value),
                    unit=md_escape(cell.unit),
                )
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_input_tables(text: str) -> list[InputCell]:
    cells: list[InputCell] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        header = split_md_row(lines[i])
        if header and header[:4] == ["Sheet", "Cell", "Label", "Value"]:
            i += 1
            if i < len(lines) and re.match(r"^\|\s*[-: ]+\|", lines[i]):
                i += 1
            while i < len(lines):
                row = split_md_row(lines[i])
                if not row:
                    break
                if len(row) < 4:
                    i += 1
                    continue
                sheet, coord, label, value = row[0], row[1], row[2], row[3]
                unit = row[4] if len(row) > 4 else ""
                if not CELL_REF_RE.match(f"{sheet}!{coord}"):
                    raise SystemExit(f"Bad cell reference in sidecar: {sheet}!{coord}")
                cells.append(
                    InputCell(
                        sheet=sheet,
                        coordinate=coord,
                        value=parse_value(value),
                        label=label,
                        unit=unit,
                    )
                )
                i += 1
            continue
        i += 1
    if not cells:
        raise SystemExit("No input tables found in sidecar (expected Sheet/Cell/Label/Value).")
    return cells


def split_md_row(line: str) -> list[str] | None:
    stripped = line.strip()
    if not stripped.startswith("|"):
        return None
    if re.match(r"^\|\s*[-:| ]+\|\s*$", stripped):
        return None
    parts = stripped.strip("|").split("|")
    return [part.strip() for part in parts]


def sheet_grid(ws: Worksheet, values: dict[tuple[int, int], Any] | None = None) -> list[list[str]]:
    max_row = ws.max_row or 0
    max_col = ws.max_column or 0
    header = [""] + [get_column_letter(c) for c in range(1, max_col + 1)]
    grid = [header]
    for r in range(1, max_row + 1):
        row = [str(r)]
        for c in range(1, max_col + 1):
            if values is not None:
                value = values.get((r, c), ws.cell(r, c).value)
            else:
                value = ws.cell(r, c).value
            row.append(fmt_value(value))
        grid.append(row)
    return grid


def print_grid(grid: list[list[str]]) -> None:
    if not grid:
        return
    widths = [max(len(row[i]) for row in grid) for i in range(len(grid[0]))]
    for i, row in enumerate(grid):
        print("  ".join(row[j].ljust(widths[j]) for j in range(len(row))))
        if i == 0:
            print("  ".join("-" * w for w in widths))


def cmd_list(_args: argparse.Namespace) -> int:
    files = list(iter_xlsx_files())
    if not files:
        print("No .xlsx workbooks found.")
        return 1
    for path in files:
        side = sidecar_path(path)
        mark = " [inputs sidecar]" if side.exists() else ""
        print(f"{path.relative_to(VAULT_ROOT)}{mark}")
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    outputs = live_outputs(path)
    payload = {
        "workbook": str(path.relative_to(VAULT_ROOT)),
        "outputs": {label: value for label, value in outputs},
    }
    if args.json:
        print(json.dumps(payload, indent=2, default=str))
        return 0
    print(path.relative_to(VAULT_ROOT))
    print("Live outputs (recalculated)")
    if not outputs:
        print("  (none)")
        return 0
    width = max(len(label) for label, _ in outputs)
    for label, value in outputs:
        print(f"  {label.ljust(width)}  {fmt_value(value)}")
    return 0


def cmd_sheets(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    wb = load_workbook(path, read_only=True, data_only=False)
    try:
        for name in wb.sheetnames:
            print(name)
    finally:
        wb.close()
    return 0


def cmd_sheet(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    wb = load_workbook(path, data_only=False)
    if args.sheet not in wb.sheetnames:
        names = ", ".join(wb.sheetnames)
        raise SystemExit(f"Sheet {args.sheet!r} not found. Sheets: {names}")
    ws = wb[args.sheet]
    values = None
    if args.values:
        fz_wb = load_formualizer(path)
        values = {}
        for r in range(1, (ws.max_row or 0) + 1):
            for c in range(1, (ws.max_column or 0) + 1):
                values[(r, c)] = fz_wb.evaluate_cell(args.sheet, r, c)
    print_grid(sheet_grid(ws, values=values))
    return 0


def dump_workbook(path: Path) -> Path:
    wb = load_workbook(path)
    cells, mode = collect_input_cells(wb)
    outputs = live_outputs(path)
    text = render_markdown(path, cells, mode, outputs)
    dest = sidecar_path(path)
    dest.write_text(text, encoding="utf-8")
    return dest


def cmd_dump(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    dest = dump_workbook(path)
    print(f"Wrote {dest.relative_to(VAULT_ROOT)} ({count_sidecar_cells(dest)} inputs)")
    return 0


def count_sidecar_cells(path: Path) -> int:
    return len(parse_input_tables(path.read_text(encoding="utf-8")))


def apply_sidecar(path: Path, sidecar: Path | None = None) -> tuple[int, dict[str, Any]]:
    side = sidecar or sidecar_path(path)
    if not side.exists():
        raise SystemExit(
            f"No sidecar at {side}. Run:\n  .venv/bin/python scripts/xlsx_model.py dump \"{path.stem}\""
        )
    cells = parse_input_tables(side.read_text(encoding="utf-8"))
    changed = apply_cells(path, cells)
    summary: dict[str, Any] = {"status": "success", "evaluated": 0, "errors": 0}
    if changed:
        summary = recalc_file(path)
    dump_workbook(path)
    return changed, summary


def cmd_apply(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    changed, summary = apply_sidecar(path)
    print(
        f"Applied {changed} cell change(s), recalculated "
        f"{summary.get('evaluated', 0)} formula(s)."
    )
    return cmd_show(args)


def cmd_set(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    cells: list[InputCell] = []
    for raw in args.assignments:
        match = SET_RE.match(raw)
        if not match:
            raise SystemExit(
                f"Bad assignment {raw!r}. Use Sheet!A1=value (example: 01_Inputs!B6=35)"
            )
        sheet, coord, value = match.group(1), match.group(2), match.group(3)
        cells.append(
            InputCell(sheet=sheet, coordinate=coord, value=parse_value(value))
        )
    changed = apply_cells(path, cells)
    summary = recalc_file(path)
    if sidecar_path(path).exists() or args.dump:
        dump_workbook(path)
    print(
        f"Set {changed} cell(s), recalculated {summary.get('evaluated', 0)} formula(s)."
    )
    return cmd_show(args)


def cmd_recalc(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    summary = recalc_file(path)
    print(
        f"Recalculated {summary.get('evaluated', 0)} formula(s), "
        f"{summary.get('errors', 0)} error(s)."
    )
    if sidecar_path(path).exists() or args.dump:
        dump_workbook(path)
    return cmd_show(args)


def cmd_check(args: argparse.Namespace) -> int:
    path = resolve_workbook(args.workbook)
    side = sidecar_path(path)
    if not side.exists():
        print(f"Missing sidecar {side.relative_to(VAULT_ROOT)}")
        return 1
    sidecar_cells = {
        (c.sheet, c.coordinate): c.value
        for c in parse_input_tables(side.read_text(encoding="utf-8"))
    }
    wb = load_workbook(path)
    xlsx_cells, _mode = collect_input_cells(wb)
    xlsx_map = {(c.sheet, c.coordinate): c.value for c in xlsx_cells}
    keys = sorted(set(sidecar_cells) | set(xlsx_map))
    diffs = []
    for key in keys:
        left = sidecar_cells.get(key, _Missing)
        right = xlsx_map.get(key, _Missing)
        if values_close(left, right):
            continue
        diffs.append((key, left, right))
    if args.json:
        print(
            json.dumps(
                {
                    "workbook": str(path.relative_to(VAULT_ROOT)),
                    "diffs": [
                        {
                            "cell": f"{sheet}!{coord}",
                            "sidecar": left if left is not _Missing else None,
                            "xlsx": right if right is not _Missing else None,
                        }
                        for (sheet, coord), left, right in diffs
                    ],
                },
                indent=2,
                default=str,
            )
        )
    else:
        if not diffs:
            print("Sidecar matches workbook inputs.")
        else:
            print(f"{len(diffs)} difference(s):")
            for (sheet, coord), left, right in diffs:
                print(f"  {sheet}!{coord}: sidecar={fmt_value(left)} xlsx={fmt_value(right)}")
    return 1 if diffs else 0


class _MissingType:
    def __repr__(self) -> str:
        return "<missing>"


_Missing = _MissingType()


def values_close(left: Any, right: Any) -> bool:
    if left is _Missing or right is _Missing:
        return False
    if isinstance(left, (int, float)) and isinstance(right, (int, float)):
        return math.isclose(float(left), float(right), rel_tol=1e-12, abs_tol=1e-9)
    return left == right


def build_parser() -> argparse.ArgumentParser:
    parent = argparse.ArgumentParser(add_help=False)
    parent.add_argument(
        "--json",
        action="store_true",
        help="JSON output for show/check",
    )
    parent.add_argument(
        "-w",
        "--workbook",
        default=None,
        help="Path or unique substring (default: GEO Complete Investment Model)",
    )

    parser = argparse.ArgumentParser(
        description="Edit vault Excel models from markdown / the CLI (cloud-friendly).",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_list = sub.add_parser("list", help="List .xlsx workbooks", parents=[parent])
    p_list.set_defaults(func=cmd_list)

    p_show = sub.add_parser("show", help="Print live Cover outputs", parents=[parent])
    p_show.set_defaults(func=cmd_show)

    p_sheets = sub.add_parser("sheets", help="List sheet names", parents=[parent])
    p_sheets.set_defaults(func=cmd_sheets)

    p_sheet = sub.add_parser(
        "sheet", help="Print a sheet as a text grid", parents=[parent]
    )
    p_sheet.add_argument("sheet", help="Sheet name")
    p_sheet.add_argument(
        "--values",
        action="store_true",
        help="Show calculated values instead of formulas",
    )
    p_sheet.set_defaults(func=cmd_sheet)

    p_dump = sub.add_parser(
        "dump", help="Write markdown sidecar from workbook inputs", parents=[parent]
    )
    p_dump.set_defaults(func=cmd_dump)

    p_apply = sub.add_parser(
        "apply",
        help="Write sidecar values into workbook and recalc",
        parents=[parent],
    )
    p_apply.set_defaults(func=cmd_apply)

    p_set = sub.add_parser(
        "set", help="Set one or more cells and recalc", parents=[parent]
    )
    p_set.add_argument(
        "assignments",
        nargs="+",
        help="Sheet!A1=value  (quote it: '01_Inputs!B6=35')",
    )
    p_set.add_argument(
        "--dump",
        action="store_true",
        help="Refresh sidecar even if it does not already exist",
    )
    p_set.set_defaults(func=cmd_set)

    p_recalc = sub.add_parser(
        "recalc", help="Recalculate formulas and cache values", parents=[parent]
    )
    p_recalc.add_argument(
        "--dump",
        action="store_true",
        help="Refresh sidecar after recalc",
    )
    p_recalc.set_defaults(func=cmd_recalc)

    p_check = sub.add_parser(
        "check", help="Diff sidecar vs workbook inputs", parents=[parent]
    )
    p_check.set_defaults(func=cmd_check)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
